# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8f1d7519681b782becee27a124f7d76ea6313384632b2f600233c33ba9236f767949d76606213b2d9c0ffa2fa495985014cee7312b77f6d67d7539cb60e7230

test:
  secret_key_base: 37c8a61a85b0e2cd1449952c74b26896dd7d2cc3dcb318b15cf9141de1f516eac9484e1bb8bae35c18fdab5bf8a7a3c4774bfc8cbbc8be149fff63efc1e40e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
